server:
  port: <%=portNumber%>


spring:
  application:
      name: <%=baseName%>
  profiles:
    active: local
<% if (security) {%>
jwt:
  signingKey: <%=parentProject%>
<%}%>

<% if (hystrix) {%> 
hystrix: 
  threadpool: 
   default:
    coreSize: 3
    maxQueueSize: -1
    queueSizeRejectionThreshold: 3
  command: 
   default: 
    circuitBreaker: 
     sleepWindowInMilliseconds: 30000
     requestVolumeThreshold: 2
    execution:
     isolation:
      strategy: THREAD
      thread:
        timeoutINMilliseconds: 500
      
  <%} %>
<% if (zuul) {%>
zuul:
  routes:
    microservice:
      path: '/json/microservice/**'
      serviceId: microservice-server
      stripPrefix: false
<%}%>    

<% if (swagger) {%>
swagger-ui:
  configuration:
    application-name: <%=baseName%>
    path: v2/api-docs
    version: 1
<%}%>





 