<% if (eureka) {%>
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/info
    health-check-url: http://localhost:${server.port}/health
    home-page-url: http://localhost:${server.port}/
<%}%>

  spring: 
<% if (jpa) {%>
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
<%}%>
   datasource:
     url: jdbc:mysql://localhost:3306/dbname?useSSL=false
     username: root
     password: admin123
     driver-class-name: com.mysql.jdbc.Driver

<% if (mongodb) {%>
   data:
     mongodb:
       uri: mongodb://localhost:27017/test

<%}%>
<%if (redis){%>

  redis:
   hostname: localhost
   port: 6380
  <%}%>