spring:
  application:
    name: <%=baseName%>
  profiles:
    active: local

server:
  port: <%=port%>
  context-path: <%=contextPath%>
         
logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO

jwt:
  signingKey: techocamp
  