#security:

#  oauth2:

#    resource:

#      jwt:

#        key-uri: http://auth.delesio.com:9999/auth/oauth/token_key

#  basic:

#    enabled: false

#  user:

#    name: admin


<% if (eureka) {%> 

eureka:

  client:

    service-url:

      defaultZone: http://eureka.techolution.qa:8761/eureka/

  instance:

    hostname: <mongodb_url>

    status-page-url: http://.techolution.com:${server.port}/info

    health-check-url: http://.techolution.com:${server.port}/health

    home-page-url: http://.techolution.com:${server.port}/

<%} %>

  spring:
<%if (jpa) {%>
   jpa:

     show-sql: true

     hibernate:

      ddl-auto: update

     properties:

       hibernate:

         dialect: org.hibernate.dialect.MySQL5Dialect
<%}%>
   datasource:

     url: jdbc:mysql://assessment-db/assessment?useSSL=false

     username: root

     password: admin123

     driver-class-name: com.mysql.jdbc.Driver


<%if (mongodb) {%>

   data:

     mongodb:

       uri: mongodb://mongo:27017/<database_name>

<%} %>
<%if (redis) {%>
redis:

   hostname: redis

   port: 
   
  <%} %>