server:
  port: <%=portNumber%>


spring:
  application:
      name: <%=baseName%>
  profiles:
    active: local
 
<% if (hystrix) {%> 
hystrix: 
  threadpool: 
   default:
    coreSize: 3
    maxQueueSize: -1
    queueSizeRejectionThreshold: 3
  command: 
   default: 
    circuitBreaker: 
     sleepWindowInMilliseconds: 30000
     requestVolumeThreshold: 2
    execution:
     isolation:
      strategy: THREAD
      thread:
        timeoutINMilliseconds: 500
      
  <%} %>
    






 